version: "3.2"
services:
  flask:
    build: .
    restart: always
    ports:
      - 80:5000
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    command: ["sh", "-c", "flask create-log-folder && flask run"]
    volumes:
      - .:/home/myuser